# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Run Eastrail Flats Monitor

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '50 18 * * *' # ~11:50am PDT for completion 12:00-12:10pm PDT
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build EastrailFlatsMonitor.csproj --no-restore
    - name: Run Monitor
      run: dotnet run --no-build -- --twilio-account-sid ${{secrets.TWILIO_ACCOUNT_SID}} --twilio-auth-token ${{secrets.TWILIO_AUTH_TOKEN}} --notification-to ${{secrets.NOTIFICATION_TO}} --notification-from ${{secrets.NOTIFICATION_FROM}}
